import CLIStateDomain
import Foundation

/// The built-in registry (§129, §130). Order matters only for executable-name
/// conflicts: earlier entries win.
enum StandardDefinitions {
    private static func tool(
        _ id: String,
        _ displayName: String,
        _ summary: String,
        _ category: ToolCategory,
        executables: [String],
        packages: [ProviderID: [String]] = [:],
        probe: VersionProbe? = VersionProbe(["--version"]),
        homepage: String,
        docs: String? = nil,
        config: [String] = [],
        native: [NativeLayout] = [],
        selfUpdate: [String]? = nil,
        updateSource: UpdateSourceDefinition? = nil,
        requiresRuntime: String? = nil,
        versionManagerNames: [String] = [],
        requiresJavaHome: Bool = false,
        leftovers: [LeftoverLocation] = []
    ) -> ToolDefinition {
        ToolDefinition(
            id: ToolID(id),
            displayName: displayName,
            summary: summary,
            category: category,
            executables: executables,
            packages: packages,
            versionProbe: probe,
            homepage: URL(string: homepage),
            documentationURL: docs.flatMap { URL(string: $0) },
            configPaths: config,
            nativeLayouts: native,
            selfUpdateArguments: selfUpdate,
            updateSource: updateSource,
            requiredRuntime: requiresRuntime,
            versionManagerNames: versionManagerNames,
            requiresJavaHome: requiresJavaHome,
            leftoverPaths: leftovers
        )
    }

    static let all: [ToolDefinition] = (runtimes + developerTools + databases + aiCLIs + packageManagers + restoreAdditions).map(withEndOfLife)

    // MARK: Runtimes

    static let runtimes: [ToolDefinition] = [
        tool("php", "PHP", "General-purpose scripting language for web development.", .runtime,
             executables: ["php", "php-config", "phpize", "pecl", "pear"],
             packages: [.homebrew: ["php"]],
             homepage: "https://www.php.net", docs: "https://www.php.net/docs.php",
             config: ["{brew}/etc/php/{mm}/php.ini", "{brew}/etc/php/{mm}/php-fpm.conf", "{brew}/etc/php/{mm}/conf.d"],
             versionManagerNames: ["php"]),
        tool("node", "Node.js", "JavaScript runtime built on V8.", .runtime,
             executables: ["node"],
             packages: [.homebrew: ["node"]],
             homepage: "https://nodejs.org", docs: "https://nodejs.org/docs/latest/api/",
             versionManagerNames: ["node", "nodejs"],
             leftovers: [LeftoverLocation("~/.node_repl_history", .data)]),
        tool("python", "Python", "Interpreted programming language.", .runtime,
             executables: ["python3", "python"],
             packages: [.homebrew: ["python"]],
             homepage: "https://www.python.org", docs: "https://docs.python.org/3/",
             versionManagerNames: ["python"],
             leftovers: [LeftoverLocation("~/.python_history", .data)]),
        tool("go", "Go", "Statically typed, compiled language from Google.", .runtime,
             executables: ["go", "gofmt"],
             packages: [.homebrew: ["go"]],
             probe: VersionProbe(["version"], pattern: #"go version go([0-9][^\s]*)"#),
             homepage: "https://go.dev", docs: "https://go.dev/doc/",
             config: ["~/Library/Application Support/go/env"],
             leftovers: [LeftoverLocation("~/Library/Caches/go-build", .cache)]),
        tool("rust", "Rust", "Systems programming language focused on safety and speed.", .runtime,
             executables: ["rustc", "rustdoc"],
             packages: [.homebrew: ["rust"]],
             homepage: "https://www.rust-lang.org", docs: "https://doc.rust-lang.org"),
        tool("ruby", "Ruby", "Dynamic, object-oriented scripting language.", .runtime,
             executables: ["ruby", "irb"],
             packages: [.homebrew: ["ruby"]],
             homepage: "https://www.ruby-lang.org", docs: "https://www.ruby-lang.org/en/documentation/",
             versionManagerNames: ["ruby"]),
        tool("java", "Java", "Java runtime and development kit.", .runtime,
             executables: ["java", "javac"],
             packages: [.homebrew: ["openjdk"]],
             probe: VersionProbe(["-version"], pattern: #"version "([^"]+)""#),
             homepage: "https://openjdk.org", docs: "https://docs.oracle.com/en/java/",
             versionManagerNames: ["java"],
             requiresJavaHome: true),
        tool("bun", "Bun", "Fast JavaScript runtime, bundler and package manager.", .runtime,
             executables: ["bun", "bunx"],
             packages: [.homebrew: ["bun"], .npm: ["bun"]],
             homepage: "https://bun.sh", docs: "https://bun.sh/docs",
             config: ["~/.bunfig.toml"],
             native: [NativeLayout(.directory("~/.bun/bin"))],
             selfUpdate: ["upgrade"],
             versionManagerNames: ["bun"],
             leftovers: [LeftoverLocation("~/.bun/install/cache", .cache)]),
        tool("deno", "Deno", "Secure JavaScript and TypeScript runtime.", .runtime,
             executables: ["deno"],
             packages: [.homebrew: ["deno"], .cargo: ["deno"]],
             homepage: "https://deno.com", docs: "https://docs.deno.com",
             native: [NativeLayout(.directory("~/.deno/bin"))],
             selfUpdate: ["upgrade"],
             versionManagerNames: ["deno"],
             leftovers: [LeftoverLocation("~/Library/Caches/deno", .cache)]),
    ]

    // MARK: Developer tools

    static let developerTools: [ToolDefinition] = [
        tool("git", "Git", "Distributed version control system.", .developerTool,
             executables: ["git"],
             packages: [.homebrew: ["git"]],
             homepage: "https://git-scm.com", docs: "https://git-scm.com/doc",
             config: ["~/.gitconfig", "~/.config/git/config"]),
        tool("gh", "GitHub CLI", "GitHub on the command line.", .developerTool,
             executables: ["gh"],
             packages: [.homebrew: ["gh"]],
             homepage: "https://cli.github.com", docs: "https://cli.github.com/manual/",
             config: ["~/.config/gh/config.yml"],
             // hosts.yml holds the OAuth token.
             leftovers: [LeftoverLocation("~/.config/gh", .config)]),
        tool("ffmpeg", "FFmpeg", "Record, convert and stream audio and video.", .developerTool,
             executables: ["ffmpeg", "ffprobe", "ffplay"],
             packages: [.homebrew: ["ffmpeg"]],
             probe: VersionProbe(["-version"]),
             homepage: "https://ffmpeg.org", docs: "https://ffmpeg.org/documentation.html"),
        tool("imagemagick", "ImageMagick", "Create, edit and convert bitmap images.", .developerTool,
             executables: ["magick"],
             packages: [.homebrew: ["imagemagick"]],
             probe: VersionProbe(["-version"], pattern: #"ImageMagick ([0-9][^\s]*)"#),
             homepage: "https://imagemagick.org", docs: "https://imagemagick.org/script/command-line-processing.php"),
        tool("wget", "Wget", "Retrieve files over HTTP, HTTPS and FTP.", .developerTool,
             executables: ["wget"],
             packages: [.homebrew: ["wget"]],
             homepage: "https://www.gnu.org/software/wget/", docs: "https://www.gnu.org/software/wget/manual/",
             config: ["~/.wgetrc"],
             leftovers: [LeftoverLocation("~/.wget-hsts", .state)]),
        tool("curl", "curl", "Transfer data with URLs.", .developerTool,
             executables: ["curl"],
             packages: [.homebrew: ["curl"]],
             homepage: "https://curl.se", docs: "https://curl.se/docs/",
             config: ["~/.curlrc"]),
        tool("jq", "jq", "Command-line JSON processor.", .developerTool,
             executables: ["jq"],
             packages: [.homebrew: ["jq"]],
             homepage: "https://jqlang.org", docs: "https://jqlang.org/manual/"),
        tool("ripgrep", "ripgrep", "Recursively search directories for a regex pattern.", .developerTool,
             executables: ["rg"],
             packages: [.homebrew: ["ripgrep"], .cargo: ["ripgrep"]],
             homepage: "https://github.com/BurntSushi/ripgrep", docs: "https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md"),
        tool("fzf", "fzf", "Command-line fuzzy finder.", .developerTool,
             executables: ["fzf"],
             packages: [.homebrew: ["fzf"]],
             homepage: "https://github.com/junegunn/fzf", docs: "https://junegunn.github.io/fzf/"),
        tool("tmux", "tmux", "Terminal multiplexer.", .developerTool,
             executables: ["tmux"],
             packages: [.homebrew: ["tmux"]],
             probe: VersionProbe(["-V"], pattern: #"tmux (?:next-)?([0-9][^\s]*)"#),
             homepage: "https://github.com/tmux/tmux", docs: "https://github.com/tmux/tmux/wiki",
             config: ["~/.tmux.conf", "~/.config/tmux/tmux.conf"]),
        tool("nginx", "nginx", "HTTP server and reverse proxy.", .developerTool,
             executables: ["nginx"],
             packages: [.homebrew: ["nginx"]],
             probe: VersionProbe(["-v"], pattern: #"nginx/([0-9][^\s]*)"#),
             homepage: "https://nginx.org", docs: "https://nginx.org/en/docs/",
             config: ["{brew}/etc/nginx/nginx.conf", "{brew}/etc/nginx/servers"]),
        tool("caddy", "Caddy", "Web server with automatic HTTPS.", .developerTool,
             executables: ["caddy"],
             packages: [.homebrew: ["caddy"]],
             probe: VersionProbe(["version"]),
             homepage: "https://caddyserver.com", docs: "https://caddyserver.com/docs/",
             config: ["{brew}/etc/Caddyfile"]),
    ]

    // MARK: Databases

    static let databases: [ToolDefinition] = [
        tool("redis", "Redis", "In-memory data store.", .database,
             executables: ["redis-server", "redis-cli"],
             packages: [.homebrew: ["redis"]],
             probe: VersionProbe(["--version"], pattern: #"v=([0-9][^\s]*)"#),
             homepage: "https://redis.io", docs: "https://redis.io/docs/latest/",
             config: ["{brew}/etc/redis.conf"],
             leftovers: [LeftoverLocation("~/.rediscli_history", .data)]),
        tool("postgresql", "PostgreSQL", "Object-relational database system.", .database,
             executables: ["psql", "postgres", "pg_ctl"],
             packages: [.homebrew: ["postgresql"]],
             homepage: "https://www.postgresql.org", docs: "https://www.postgresql.org/docs/",
             config: ["{brew}/var/postgresql@{major}/postgresql.conf", "~/.psqlrc"],
             leftovers: [LeftoverLocation("~/.psql_history", .data)]),
        tool("mysql", "MySQL", "Relational database server.", .database,
             executables: ["mysql", "mysqld"],
             packages: [.homebrew: ["mysql"]],
             homepage: "https://www.mysql.com", docs: "https://dev.mysql.com/doc/",
             config: ["{brew}/etc/my.cnf", "~/.my.cnf"],
             leftovers: [LeftoverLocation("~/.mysql_history", .data)]),
        tool("mongodb", "MongoDB", "Document-oriented database server.", .database,
             executables: ["mongod"],
             packages: [.homebrew: ["mongodb-community"]],
             probe: VersionProbe(["--version"], pattern: #"db version v([0-9][^\s]*)"#),
             homepage: "https://www.mongodb.com", docs: "https://www.mongodb.com/docs/manual/",
             config: ["{brew}/etc/mongod.conf"]),
        tool("sqlite", "SQLite", "Self-contained SQL database engine.", .database,
             executables: ["sqlite3"],
             packages: [.homebrew: ["sqlite"]],
             homepage: "https://sqlite.org", docs: "https://sqlite.org/docs.html",
             config: ["~/.sqliterc"],
             leftovers: [LeftoverLocation("~/.sqlite_history", .data)]),
    ]

    // MARK: AI CLIs

    static let aiCLIs: [ToolDefinition] = [
        tool("claude-code", "Claude Code", "Anthropic's agentic coding tool for the terminal.", .aiCLI,
             executables: ["claude"],
             packages: [.npm: ["@anthropic-ai/claude-code"], .homebrew: ["claude-code"]],
             homepage: "https://www.anthropic.com/claude-code", docs: "https://docs.anthropic.com/en/docs/claude-code/overview",
             config: ["~/.claude/settings.json", "~/.claude.json"],
             native: [NativeLayout(.versionedRoot("~/.local/share/claude/versions"))],
             selfUpdate: ["update"],
             updateSource: .npmDistTags(package: "@anthropic-ai/claude-code", channel: "latest"),
             leftovers: [
                LeftoverLocation("~/.claude", .data),
                LeftoverLocation("~/.claude.json", .config),
                // MCP server logs, written through env-paths' `claude-cli` name.
                LeftoverLocation("~/Library/Caches/claude-cli-nodejs", .logs),
             ]),
        tool("gemini-cli", "Gemini CLI", "Google's Gemini agent for the terminal.", .aiCLI,
             executables: ["gemini"],
             packages: [.npm: ["@google/gemini-cli"], .homebrew: ["gemini-cli"]],
             homepage: "https://github.com/google-gemini/gemini-cli", docs: "https://github.com/google-gemini/gemini-cli/tree/main/docs",
             config: ["~/.gemini/settings.json"],
             leftovers: [LeftoverLocation("~/.gemini", .data)]),
        tool("kimi-cli", "Kimi CLI", "Moonshot AI's Kimi coding agent for the terminal.", .aiCLI,
             executables: ["kimi", "kimi-cli"],
             packages: [.uv: ["kimi-cli"], .pipx: ["kimi-cli"]],
             homepage: "https://github.com/MoonshotAI/kimi-cli",
             // Kimi Code's standalone installer: its receipt is `updates/install.json`, and the
             // binary downloads ripgrep and fd into `$KIMI_CODE_HOME/bin` for its own use.
             native: [NativeLayout(.directory("~/.kimi-code/bin"), marker: "~/.kimi-code/updates/install.json", bundlesHelpers: true)]),
        tool("codex", "Codex CLI", "OpenAI's coding agent for the terminal.", .aiCLI,
             executables: ["codex"],
             packages: [.npm: ["@openai/codex"], .homebrew: ["codex"]],
             homepage: "https://github.com/openai/codex", docs: "https://developers.openai.com/codex/cli",
             config: ["~/.codex/config.toml"],
             leftovers: [LeftoverLocation("~/.codex", .data)]),
        tool("opencode", "opencode", "Open-source AI coding agent for the terminal.", .aiCLI,
             executables: ["opencode"],
             packages: [.npm: ["opencode-ai"], .homebrew: ["opencode"]],
             homepage: "https://opencode.ai", docs: "https://opencode.ai/docs",
             config: ["~/.config/opencode/opencode.json"],
             native: [NativeLayout(.directory("~/.opencode/bin"))],
             selfUpdate: ["upgrade"],
             // auth.json and session storage.
             leftovers: [LeftoverLocation("~/.local/share/opencode", .data)]),
        tool("aider", "Aider", "AI pair programming in the terminal.", .aiCLI,
             executables: ["aider"],
             packages: [.uv: ["aider-chat"], .pipx: ["aider-chat"], .homebrew: ["aider"]],
             homepage: "https://aider.chat", docs: "https://aider.chat/docs/",
             config: ["~/.aider.conf.yml"]),
        tool("qwen-code", "Qwen Code", "Alibaba's Qwen coding agent for the terminal.", .aiCLI,
             executables: ["qwen"],
             packages: [.npm: ["@qwen-code/qwen-code"], .homebrew: ["qwen-code"]],
             homepage: "https://github.com/QwenLM/qwen-code",
             config: ["~/.qwen/settings.json"],
             leftovers: [LeftoverLocation("~/.qwen", .data)]),
        tool("copilot-cli", "GitHub Copilot CLI", "GitHub Copilot's coding agent for the terminal.", .aiCLI,
             executables: ["copilot"],
             packages: [.npm: ["@github/copilot"], .homebrew: ["copilot-cli"]],
             homepage: "https://github.com/github/copilot-cli", docs: "https://docs.github.com/en/copilot",
             config: ["~/.copilot/config.json"],
             leftovers: [LeftoverLocation("~/.copilot", .data)]),
    ]

    // MARK: Package managers

    static let packageManagers: [ToolDefinition] = [
        tool("homebrew", "Homebrew", "The missing package manager for macOS.", .packageManager,
             executables: ["brew"],
             homepage: "https://brew.sh", docs: "https://docs.brew.sh",
             native: [
                NativeLayout(.file("/opt/homebrew/bin/brew"), provider: .homebrew),
                NativeLayout(.file("/usr/local/Homebrew/bin/brew"), provider: .homebrew),
                NativeLayout(.file("/usr/local/bin/brew"), provider: .homebrew),
             ]),
        tool("npm", "npm", "Package manager bundled with Node.js.", .packageManager,
             executables: ["npm", "npx"],
             packages: [.npm: ["npm"]],
             homepage: "https://www.npmjs.com", docs: "https://docs.npmjs.com",
             config: ["~/.npmrc"],
             requiresRuntime: "node",
             leftovers: [LeftoverLocation("~/.npm/_cacache", .cache)]),
        tool("pnpm", "pnpm", "Fast, disk-efficient Node.js package manager.", .packageManager,
             executables: ["pnpm", "pnpx"],
             packages: [.npm: ["pnpm"], .homebrew: ["pnpm"]],
             homepage: "https://pnpm.io", docs: "https://pnpm.io/motivation",
             config: ["~/Library/Preferences/pnpm/rc"]),
        tool("yarn", "Yarn", "Node.js package manager.", .packageManager,
             executables: ["yarn", "yarnpkg"],
             packages: [.npm: ["yarn"], .homebrew: ["yarn"]],
             homepage: "https://yarnpkg.com", docs: "https://yarnpkg.com/getting-started",
             config: ["~/.yarnrc", "~/.yarnrc.yml"],
             leftovers: [LeftoverLocation("~/Library/Caches/Yarn", .cache)]),
        tool("pip", "pip", "Package installer for Python.", .packageManager,
             executables: ["pip3", "pip"],
             homepage: "https://pip.pypa.io", docs: "https://pip.pypa.io/en/stable/",
             config: ["~/.config/pip/pip.conf", "~/Library/Application Support/pip/pip.conf"],
             requiresRuntime: "python3",
             leftovers: [LeftoverLocation("~/Library/Caches/pip", .cache)]),
        tool("pipx", "pipx", "Install and run Python applications in isolated environments.", .packageManager,
             executables: ["pipx"],
             packages: [.homebrew: ["pipx"]],
             homepage: "https://pipx.pypa.io", docs: "https://pipx.pypa.io/stable/"),
        tool("uv", "uv", "Extremely fast Python package and project manager.", .packageManager,
             executables: ["uv", "uvx"],
             packages: [.homebrew: ["uv"], .pipx: ["uv"]],
             homepage: "https://docs.astral.sh/uv/", docs: "https://docs.astral.sh/uv/",
             config: ["~/.config/uv/uv.toml"],
             native: [
                NativeLayout(.file("~/.local/bin/uv"), marker: "~/.config/uv/uv-receipt.json"),
                NativeLayout(.file("~/.local/bin/uvx"), marker: "~/.config/uv/uv-receipt.json"),
             ],
             selfUpdate: ["self", "update"],
             leftovers: [LeftoverLocation("~/.cache/uv", .cache)]),
        tool("cargo", "Cargo", "Rust package manager and build tool.", .packageManager,
             executables: ["cargo"],
             homepage: "https://doc.rust-lang.org/cargo/", docs: "https://doc.rust-lang.org/cargo/",
             config: ["~/.cargo/config.toml"],
             // Downloaded crate archives, index and sources; cargo fetches them again.
             leftovers: [LeftoverLocation("~/.cargo/registry", .cache)]),
        tool("rustup", "rustup", "Rust toolchain installer.", .packageManager,
             executables: ["rustup"],
             packages: [.homebrew: ["rustup"]],
             homepage: "https://rustup.rs", docs: "https://rust-lang.github.io/rustup/",
             config: ["~/.rustup/settings.toml"],
             selfUpdate: ["self", "update"]),
        tool("composer", "Composer", "Dependency manager for PHP.", .packageManager,
             executables: ["composer"],
             packages: [.homebrew: ["composer"]],
             homepage: "https://getcomposer.org", docs: "https://getcomposer.org/doc/",
             config: ["~/.composer/config.json", "~/.config/composer/config.json"],
             requiresRuntime: "php"),
        tool("gem", "RubyGems", "Package manager for Ruby.", .packageManager,
             executables: ["gem"],
             homepage: "https://rubygems.org", docs: "https://guides.rubygems.org",
             config: ["~/.gemrc"],
             requiresRuntime: "ruby"),
    ]
}
